### ISSUE TITLE
Manifest file is missing or unreadable

### ISSUE THREAD

**Issue by SphaeroX** [stephancasas/thingiverse-stl-downloader#1]
6. Browse to and select the directory where you unzipped the extension release.

Than i got this Error:

```
Error loading the extension
File
~\Downloads\thingiverse-stl-downloader-master\thingiverse-stl-downloader-master
Error
Manifest file is missing or unreadable
Manifest could not be loaded.
```

**Comment by SphaeroX** [comment]
This happens when you download the extension directly from the repository, with the release download everything works :)

**Comment by stephancasas** [comment]
Glad you got it working. Enjoy!
